name: "intake-agent"
description: "Agent to process inbound leads from Twilio SMS and PWA, validate, estimate and enqueue quote requests."
author: "BMad Builder"
version: "0.1.0"
type: "autonomous"

config_source: "{project-root}/bmad/bmb/config.yaml"

runtime: deno
entry: "handler.ts"

triggers:
  - type: webhook
    path: /webhooks/twilio
    method: POST

outputs:
  - events_outbox

description_long: |
  Intake Agent receives Twilio inbound SMS webhooks and PWA lead POSTs, validates payloads, runs pricing heuristics or marks for manual review, and writes lead records to Supabase and events to the outbox. Designed to be idempotent and safe to re-run.
